version: '3.8'

services:
  flask_app_dev:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    container_name: flask_app_dev
    restart: always

  flask_app_prod:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    container_name: flask_app_prod
    restart: always

