apiVersion: v1
kind: Service
metadata:
  name: mental-health-service
spec:
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
  selector:
    app: mental-health-app
