name: Continous Monitoring

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:      

jobs:
  check-drift:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use system Python
        run: |
          python3.8 -m pip install --upgrade pip --user
          python3.8 -m pip install pandas nannyml --user
          python3.8 drift_detector.py


      - name: Trigger retraining if drift detected
        if: success()
        run: |
          if grep -q "Drift detected" detect_drift_output.log; then
            echo "Drift detected, triggering retraining..."

            API_URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/ct.yml/dispatches"
            
            echo "Attempting to call API URL: $API_URL"

            curl -v -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              "$API_URL" \  
              -d '{"ref":"dev"}'
          else
            echo "No drift detected. No action needed."
          fi
            

