name: Continous Monitoring

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:      

jobs:
  check-drift:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use system Python
        run: |
          python3.8 -m pip install --upgrade pip --user
          python3.8 -m pip install pandas nannyml --user
          python3.8 drift_detector.py


      - name: Trigger retraining if drift detected
        if: success() 
        run: |
          if grep -q "Drift detected" detect_drift_output.log; then
            echo "Drift detected."
            echo "TRIGGER_CT=true" >> $GITHUB_ENV 
          else
            echo "No drift detected. No action needed."
            echo "TRIGGER_CT=false" >> $GITHUB_ENV
          fi

      - name: Dispatch Continuous Training Workflow
        if: env.TRIGGER_CT == 'true' 
        uses: benc-uk/workflow-dispatch@v1 
        with:
          workflow: ct.yml 
          token: ${{ secrets.PAT_TOKEN }}
          ref: dev
            

