name: Continuous Training

on:
  workflow_dispatch:
  repository_dispatch:
    types: [training]

jobs:
  retrain-model:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          python3.8 -m pip install --upgrade pip --user
          python3.8 -m pip install pandas scikit-learn joblib --user

      - name: Run model training
        run: |
          python3.8 retrain_model.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

      - name: Check model accuracy
        id: accuracy
        run: |
          if [ ! -f accuracy.txt ]; then
            echo "Error: accuracy.txt not found"
            exit 1
          fi
          ACCURACY=$(cat accuracy.txt)
          echo "Model accuracy: $ACCURACY"
          PASS=$(python3 -c "print('true' if float('$ACCURACY') >= 0.90 else 'false')")
          echo "pass=$PASS" >> $GITHUB_OUTPUT


          # Fail job if accuracy below threshold to stop workflow
          if [ "$PASS" != "true" ]; then
            echo "Model accuracy below threshold, stopping workflow."
            exit 1
          fi

      - name: Trigger build and deploy workflow
        if: steps.accuracy.outputs.pass == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Pull and Publish Docker Image 
          token: ${{ secrets.PAT_TOKEN }} 
          ref: dev 
          inputs: '{
            "model_artifact_run_id": "${{ github.run_id }}",
            "target_branch": "dev"
          }'
