name: Promote Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: echo "APP_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV


    - name: Deploy to server
      env:
        APP_ENV: ${{ github.event.inputs.environment }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        if [ "$APP_ENV" = "dev" ]; then
          PORT=5001
        else
          PORT=5000
        fi
          docker pull ${DOCKER_USERNAME}/mental-health:${APP_ENV} &&
          docker stop flask_app_${APP_ENV} || true &&
          docker rm flask_app_${APP_ENV} || true &&
          docker run -d --name flask_app_${APP_ENV} -p ${PORT}:5000 ${DOCKER_USERNAME}/mental-health:${APP_ENV} 