name: Promote Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      version_tag:
        description: 'Docker image version to deploy (e.g., dev23, prod19)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "APP_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        if [ -z "${{ github.event.inputs.version_tag }}" ]; then
          echo "IMAGE_TAG=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ github.event.inputs.version_tag }}" >> $GITHUB_ENV
        fi

    - name: Deploy to server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        APP_ENV: ${{ env.APP_ENV }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        if [ "$APP_ENV" = "dev" ]; then
          PORT=5001
        else
          PORT=5000
        fi

        echo "Deploying image: ${DOCKER_USERNAME}/mental-health:${IMAGE_TAG}"

        docker pull ${DOCKER_USERNAME}/mental-health:${IMAGE_TAG} &&
        docker stop flask_app_${APP_ENV} || true &&
        docker rm flask_app_${APP_ENV} || true &&
        docker run -d --name flask_app_${APP_ENV} -p ${PORT}:5000 ${DOCKER_USERNAME}/mental-health:${IMAGE_TAG}
