name: Test Drift

on:
  workflow_dispatch:

jobs:
  drift:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate data drift
        run: python simulate_drift.py

