name: Pull and Publish Docker Image

on:
  push:
    branches: [dev, main]

jobs:
  build-test-publish:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set image tag based on branch
      id : vars
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"

        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "TAG=prod" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "TAG=dev" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == RB* ]]; then
          git fetch origin main dev
        
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "TAG=prod-${BRANCH_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=dev-${BRANCH_NAME}" >> $GITHUB_ENV
          fi
        else
          echo "TAG=latest" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.TAG }}

    - name: Run tests inside Docker container
      run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.TAG }} pytest -s

    - name: Push Docker image  
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.TAG }}

