name: Pull and Publish Docker Image

on:
  push:
    branches: [dev, main, RB-*]

jobs:
  build-test-publish:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set image tag based on branch
      id: vars
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        RUN_NUM=${GITHUB_RUN_NUMBER}


        if [[ "$BRANCH_NAME" == "main" ]]; then
          ENV=prod
        elif [[ "$BRANCH_NAME" == "dev" ]]; then
          ENV=dev
        else
          ENV=latest
        fi

        VERSION_TAG="${ENV}${RUN_NUM}"

        echo "ENV=$ENV" >> $GITHUB_ENV
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.VERSION_TAG }} -t ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.ENV }}


    - name: Run tests inside Docker container
      run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.VERSION_TAG }} pytest -s


    - name: Push Docker image  
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mental-health:${{ env.VERSION_TAG }}


