name: Pull and Publish Docker Image

on:
  pull_request:
    branches: [dev, main]

jobs:
  build-test-publish:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest -s

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/mental-health:latest

    - name: Run tests inside Docker container
      run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/mental-health:latest pytest -s

    - name: Push Docker image  
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mental-health:latest

