name: Redeploy Docker Container

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (e.g., dev, prod)'
        required: true
        default: 'prod'

jobs:
  redeploy:
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Pull and restart Docker container
        run: |
          TAG="${{ github.event.inputs.image_tag }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/mental-health:$TAG
          docker stop mental-health-container || true
          docker rm mental-health-container || true
          docker run -d --name mental-health-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/mental-health:$TAG
